export interface WordEntry {
  word: string;
  hints: { Easy: string; Medium: string; Hard: string };
}

export const wordBank: Record<string, WordEntry[]> = {
  Fruits: [
    { word: 'Apple', hints: { Easy: 'Red', Medium: 'Gravity', Hard: 'Newton' } },
    { word: 'Banana', hints: { Easy: 'Yellow', Medium: 'Monkey', Hard: 'Curved' } },
    { word: 'Mango', hints: { Easy: 'Tropical', Medium: 'King', Hard: 'Ataulfo' } },
    { word: 'Strawberry', hints: { Easy: 'Red', Medium: 'Wimbledon', Hard: 'Shortcake' } },
    { word: 'Watermelon', hints: { Easy: 'Green', Medium: 'Summer', Hard: 'Rind' } },
    { word: 'Grapes', hints: { Easy: 'Purple', Medium: 'Wine', Hard: 'Vineyard' } },
    { word: 'Pineapple', hints: { Easy: 'Spiky', Medium: 'Hawaii', Hard: 'Bromelain' } },
    { word: 'Orange', hints: { Easy: 'Citrus', Medium: 'Vitamin', Hard: 'Zest' } },
    { word: 'Peach', hints: { Easy: 'Fuzzy', Medium: 'Georgia', Hard: 'Drupe' } },
    { word: 'Cherry', hints: { Easy: 'Small', Medium: 'Pie', Hard: 'Maraschino' } },
    { word: 'Lemon', hints: { Easy: 'Sour', Medium: 'Lemonade', Hard: 'Zesty' } },
    { word: 'Coconut', hints: { Easy: 'Brown', Medium: 'Beach', Hard: 'Endosperm' } },
    { word: 'Papaya', hints: { Easy: 'Orange', Medium: 'Tropical', Hard: 'Papain' } },
    { word: 'Kiwi', hints: { Easy: 'Green', Medium: 'New Zealand', Hard: 'Actinidia' } },
    { word: 'Blueberry', hints: { Easy: 'Blue', Medium: 'Antioxidant', Hard: 'Muffin' } },
    { word: 'Avocado', hints: { Easy: 'Green', Medium: 'Toast', Hard: 'Persea' } },
    { word: 'Pomegranate', hints: { Easy: 'Seeds', Medium: 'Juice', Hard: 'Persephone' } },
    { word: 'Lychee', hints: { Easy: 'Sweet', Medium: 'Asian', Hard: 'Aril' } },
    { word: 'Guava', hints: { Easy: 'Pink', Medium: 'Tropical', Hard: 'Psidium' } },
    { word: 'Fig', hints: { Easy: 'Sweet', Medium: 'Newton', Hard: 'Syconium' } },
    { word: 'Plum', hints: { Easy: 'Purple', Medium: 'Prune', Hard: 'Damson' } },
    { word: 'Pear', hints: { Easy: 'Green', Medium: 'Teardrop', Hard: 'Bosc' } },
    { word: 'Raspberry', hints: { Easy: 'Red', Medium: 'Jam', Hard: 'Aggregate' } },
    { word: 'Blackberry', hints: { Easy: 'Dark', Medium: 'Thorny', Hard: 'Drupelet' } },
    { word: 'Tangerine', hints: { Easy: 'Orange', Medium: 'Peeling', Hard: 'Clementine' } },
    { word: 'Lime', hints: { Easy: 'Green', Medium: 'Margarita', Hard: 'Key' } },
    { word: 'Melon', hints: { Easy: 'Round', Medium: 'Summer', Hard: 'Cantaloupe' } },
    { word: 'Apricot', hints: { Easy: 'Orange', Medium: 'Jam', Hard: 'Prunus' } },
    { word: 'Durian', hints: { Easy: 'Smelly', Medium: 'Spiky', Hard: 'Banned' } },
    { word: 'Jackfruit', hints: { Easy: 'Large', Medium: 'Meat', Hard: 'Artocarpus' } },
  ],

  Animals: [
    { word: 'Elephant', hints: { Easy: 'Trunk', Medium: 'Memory', Hard: 'Pachyderm' } },
    { word: 'Lion', hints: { Easy: 'Roar', Medium: 'Pride', Hard: 'Savanna' } },
    { word: 'Penguin', hints: { Easy: 'Waddle', Medium: 'Antarctica', Hard: 'Flightless' } },
    { word: 'Giraffe', hints: { Easy: 'Tall', Medium: 'Spots', Hard: 'Ossicones' } },
    { word: 'Dolphin', hints: { Easy: 'Smart', Medium: 'Sonar', Hard: 'Cetacean' } },
    { word: 'Tiger', hints: { Easy: 'Stripes', Medium: 'India', Hard: 'Apex' } },
    { word: 'Gorilla', hints: { Easy: 'Strong', Medium: 'Jungle', Hard: 'Silverback' } },
    { word: 'Kangaroo', hints: { Easy: 'Pouch', Medium: 'Australia', Hard: 'Joey' } },
    { word: 'Cheetah', hints: { Easy: 'Fast', Medium: 'Spots', Hard: 'Acinonyx' } },
    { word: 'Panda', hints: { Easy: 'Black', Medium: 'Bamboo', Hard: 'Endangered' } },
    { word: 'Crocodile', hints: { Easy: 'Teeth', Medium: 'Swamp', Hard: 'Archosaur' } },
    { word: 'Parrot', hints: { Easy: 'Colorful', Medium: 'Mimic', Hard: 'Psittacine' } },
    { word: 'Shark', hints: { Easy: 'Fins', Medium: 'Ocean', Hard: 'Cartilaginous' } },
    { word: 'Owl', hints: { Easy: 'Wise', Medium: 'Nocturnal', Hard: 'Strigiform' } },
    { word: 'Wolf', hints: { Easy: 'Howl', Medium: 'Pack', Hard: 'Canis' } },
    { word: 'Bear', hints: { Easy: 'Hibernate', Medium: 'Honey', Hard: 'Ursine' } },
    { word: 'Zebra', hints: { Easy: 'Stripes', Medium: 'Africa', Hard: 'Equid' } },
    { word: 'Flamingo', hints: { Easy: 'Pink', Medium: 'Standing', Hard: 'Phoenicopterus' } },
    { word: 'Koala', hints: { Easy: 'Cute', Medium: 'Eucalyptus', Hard: 'Marsupial' } },
    { word: 'Octopus', hints: { Easy: 'Arms', Medium: 'Ink', Hard: 'Cephalopod' } },
    { word: 'Peacock', hints: { Easy: 'Feathers', Medium: 'Display', Hard: 'Iridescent' } },
    { word: 'Chameleon', hints: { Easy: 'Color', Medium: 'Camouflage', Hard: 'Casque' } },
    { word: 'Platypus', hints: { Easy: 'Weird', Medium: 'Australia', Hard: 'Monotreme' } },
    { word: 'Sloth', hints: { Easy: 'Slow', Medium: 'Hanging', Hard: 'Bradypodidae' } },
    { word: 'Hippo', hints: { Easy: 'Big', Medium: 'River', Hard: 'Amphibious' } },
    { word: 'Meerkat', hints: { Easy: 'Standing', Medium: 'Desert', Hard: 'Sentinel' } },
    { word: 'Axolotl', hints: { Easy: 'Gills', Medium: 'Mexico', Hard: 'Neotenic' } },
    { word: 'Narwhal', hints: { Easy: 'Horn', Medium: 'Arctic', Hard: 'Unicorn' } },
    { word: 'Capybara', hints: { Easy: 'Rodent', Medium: 'Swimming', Hard: 'Hydrochoerus' } },
    { word: 'Mantis', hints: { Easy: 'Praying', Medium: 'Camouflage', Hard: 'Predatory' } },
  ],

  Countries: [
    { word: 'Japan', hints: { Easy: 'Sushi', Medium: 'Sakura', Hard: 'Nippon' } },
    { word: 'Brazil', hints: { Easy: 'Carnival', Medium: 'Amazon', Hard: 'Caipirinha' } },
    { word: 'France', hints: { Easy: 'Eiffel', Medium: 'Baguette', Hard: 'Gaul' } },
    { word: 'Egypt', hints: { Easy: 'Pyramids', Medium: 'Pharaoh', Hard: 'Hieroglyphics' } },
    { word: 'Australia', hints: { Easy: 'Kangaroo', Medium: 'Outback', Hard: 'Oceania' } },
    { word: 'India', hints: { Easy: 'Curry', Medium: 'Ganges', Hard: 'Subcontinent' } },
    { word: 'Italy', hints: { Easy: 'Pizza', Medium: 'Colosseum', Hard: 'Peninsula' } },
    { word: 'China', hints: { Easy: 'Wall', Medium: 'Dragon', Hard: 'Dynasty' } },
    { word: 'Mexico', hints: { Easy: 'Tacos', Medium: 'Aztec', Hard: 'Mariachi' } },
    { word: 'Russia', hints: { Easy: 'Cold', Medium: 'Matryoshka', Hard: 'Tsar' } },
    { word: 'Canada', hints: { Easy: 'Maple', Medium: 'Hockey', Hard: 'Confederation' } },
    { word: 'Greece', hints: { Easy: 'Columns', Medium: 'Olympics', Hard: 'Hellenic' } },
    { word: 'Spain', hints: { Easy: 'Bullfight', Medium: 'Flamenco', Hard: 'Iberian' } },
    { word: 'Germany', hints: { Easy: 'Bratwurst', Medium: 'Oktoberfest', Hard: 'Reich' } },
    { word: 'Argentina', hints: { Easy: 'Tango', Medium: 'Pampas', Hard: 'Gaucho' } },
    { word: 'Nigeria', hints: { Easy: 'Africa', Medium: 'Lagos', Hard: 'Naira' } },
    { word: 'Thailand', hints: { Easy: 'Temple', Medium: 'Pad Thai', Hard: 'Baht' } },
    { word: 'Kenya', hints: { Easy: 'Safari', Medium: 'Savanna', Hard: 'Nairobi' } },
    { word: 'Norway', hints: { Easy: 'Fjord', Medium: 'Aurora', Hard: 'Viking' } },
    { word: 'Turkey', hints: { Easy: 'Istanbul', Medium: 'Bosphorus', Hard: 'Ottoman' } },
    { word: 'Peru', hints: { Easy: 'Machu Picchu', Medium: 'Inca', Hard: 'Quechua' } },
    { word: 'Iceland', hints: { Easy: 'Volcano', Medium: 'Geyser', Hard: 'Nordic' } },
    { word: 'Morocco', hints: { Easy: 'Sahara', Medium: 'Medina', Hard: 'Maghreb' } },
    { word: 'Vietnam', hints: { Easy: 'Pho', Medium: 'Mekong', Hard: 'Indochina' } },
    { word: 'Colombia', hints: { Easy: 'Coffee', Medium: 'Cartagena', Hard: 'Cumbia' } },
    { word: 'Portugal', hints: { Easy: 'Lisbon', Medium: 'Fado', Hard: 'Lusophone' } },
    { word: 'Ethiopia', hints: { Easy: 'Coffee', Medium: 'Marathon', Hard: 'Habesha' } },
    { word: 'Philippines', hints: { Easy: 'Islands', Medium: 'Adobo', Hard: 'Archipelago' } },
    { word: 'Sweden', hints: { Easy: 'IKEA', Medium: 'Meatballs', Hard: 'Scandinavia' } },
    { word: 'Pakistan', hints: { Easy: 'Cricket', Medium: 'Himalaya', Hard: 'Urdu' } },
  ],

  Sports: [
    { word: 'Basketball', hints: { Easy: 'Hoop', Medium: 'Dribble', Hard: 'Naismith' } },
    { word: 'Soccer', hints: { Easy: 'Goal', Medium: 'Offside', Hard: 'Futbol' } },
    { word: 'Tennis', hints: { Easy: 'Racket', Medium: 'Deuce', Hard: 'Wimbledon' } },
    { word: 'Swimming', hints: { Easy: 'Pool', Medium: 'Stroke', Hard: 'Freestyle' } },
    { word: 'Baseball', hints: { Easy: 'Bat', Medium: 'Innings', Hard: 'Shortstop' } },
    { word: 'Golf', hints: { Easy: 'Club', Medium: 'Birdie', Hard: 'Albatross' } },
    { word: 'Boxing', hints: { Easy: 'Punch', Medium: 'Rounds', Hard: 'Southpaw' } },
    { word: 'Volleyball', hints: { Easy: 'Spike', Medium: 'Serve', Hard: 'Libero' } },
    { word: 'Rugby', hints: { Easy: 'Tackle', Medium: 'Scrum', Hard: 'Lineout' } },
    { word: 'Cycling', hints: { Easy: 'Pedal', Medium: 'Tour', Hard: 'Velodrome' } },
    { word: 'Wrestling', hints: { Easy: 'Pin', Medium: 'Grapple', Hard: 'Sumo' } },
    { word: 'Archery', hints: { Easy: 'Arrow', Medium: 'Bullseye', Hard: 'Quiver' } },
    { word: 'Skiing', hints: { Easy: 'Snow', Medium: 'Slalom', Hard: 'Moguls' } },
    { word: 'Surfing', hints: { Easy: 'Wave', Medium: 'Pipeline', Hard: 'Barrel' } },
    { word: 'Gymnastics', hints: { Easy: 'Flip', Medium: 'Vault', Hard: 'Pommel' } },
    { word: 'Fencing', hints: { Easy: 'Sword', Medium: 'Parry', Hard: 'Epee' } },
    { word: 'Badminton', hints: { Easy: 'Shuttle', Medium: 'Smash', Hard: 'Birdie' } },
    { word: 'Rowing', hints: { Easy: 'Oar', Medium: 'Regatta', Hard: 'Coxswain' } },
    { word: 'Diving', hints: { Easy: 'Splash', Medium: 'Springboard', Hard: 'Tuck' } },
    { word: 'Hockey', hints: { Easy: 'Puck', Medium: 'Penalty', Hard: 'Slap shot' } },
    { word: 'Polo', hints: { Easy: 'Horse', Medium: 'Mallet', Hard: 'Chukker' } },
    { word: 'Curling', hints: { Easy: 'Ice', Medium: 'Broom', Hard: 'Hack' } },
    { word: 'Taekwondo', hints: { Easy: 'Kick', Medium: 'Belt', Hard: 'Dobok' } },
    { word: 'Judo', hints: { Easy: 'Throw', Medium: 'Gi', Hard: 'Ippon' } },
    { word: 'Skateboarding', hints: { Easy: 'Trick', Medium: 'Halfpipe', Hard: 'Ollie' } },
    { word: 'Triathlon', hints: { Easy: 'Three', Medium: 'Ironman', Hard: 'Transition' } },
    { word: 'Snooker', hints: { Easy: 'Cue', Medium: 'Break', Hard: 'Cannons' } },
    { word: 'Darts', hints: { Easy: 'Bullseye', Medium: 'Double', Hard: 'Oche' } },
    { word: 'Karate', hints: { Easy: 'Chop', Medium: 'Kata', Hard: 'Dojo' } },
    { word: 'Handball', hints: { Easy: 'Throw', Medium: 'Goalkeeper', Hard: 'Pivot' } },
  ],

  Food: [
    { word: 'Pizza', hints: { Easy: 'Cheese', Medium: 'Naples', Hard: 'Margherita' } },
    { word: 'Sushi', hints: { Easy: 'Raw', Medium: 'Wasabi', Hard: 'Nigiri' } },
    { word: 'Burger', hints: { Easy: 'Bun', Medium: 'Patty', Hard: 'Brioche' } },
    { word: 'Pasta', hints: { Easy: 'Italian', Medium: 'Al dente', Hard: 'Semolina' } },
    { word: 'Tacos', hints: { Easy: 'Shell', Medium: 'Salsa', Hard: 'Tortilla' } },
    { word: 'Ramen', hints: { Easy: 'Noodles', Medium: 'Broth', Hard: 'Umami' } },
    { word: 'Steak', hints: { Easy: 'Beef', Medium: 'Rare', Hard: 'Ribeye' } },
    { word: 'Spaghetti', hints: { Easy: 'Long', Medium: 'Bolognese', Hard: 'Carbonara' } },
    { word: 'Croissant', hints: { Easy: 'Flaky', Medium: 'Butter', Hard: 'Laminated' } },
    { word: 'Pancakes', hints: { Easy: 'Syrup', Medium: 'Fluffy', Hard: 'Griddle' } },
    { word: 'Cheesecake', hints: { Easy: 'Creamy', Medium: 'New York', Hard: 'Springform' } },
    { word: 'Curry', hints: { Easy: 'Spicy', Medium: 'India', Hard: 'Turmeric' } },
    { word: 'Paella', hints: { Easy: 'Rice', Medium: 'Spain', Hard: 'Saffron' } },
    { word: 'Pho', hints: { Easy: 'Soup', Medium: 'Vietnam', Hard: 'Anise' } },
    { word: 'Dumplings', hints: { Easy: 'Stuffed', Medium: 'Steamed', Hard: 'Dim sum' } },
    { word: 'Waffles', hints: { Easy: 'Grid', Medium: 'Belgium', Hard: 'Batter' } },
    { word: 'Sashimi', hints: { Easy: 'Sliced', Medium: 'Fish', Hard: 'Omakase' } },
    { word: 'Kebab', hints: { Easy: 'Skewer', Medium: 'Grilled', Hard: 'Doner' } },
    { word: 'Churros', hints: { Easy: 'Fried', Medium: 'Spain', Hard: 'Chocolate' } },
    { word: 'Moussaka', hints: { Easy: 'Layers', Medium: 'Greece', Hard: 'Bechamel' } },
    { word: 'Biryani', hints: { Easy: 'Rice', Medium: 'Spices', Hard: 'Dum' } },
    { word: 'Falafel', hints: { Easy: 'Fried', Medium: 'Chickpea', Hard: 'Levantine' } },
    { word: 'Tiramisu', hints: { Easy: 'Coffee', Medium: 'Italy', Hard: 'Mascarpone' } },
    { word: 'Lasagna', hints: { Easy: 'Layers', Medium: 'Bolognese', Hard: 'Bechamel' } },
    { word: 'Shawarma', hints: { Easy: 'Wrap', Medium: 'Rotisserie', Hard: 'Levantine' } },
    { word: 'Tempura', hints: { Easy: 'Fried', Medium: 'Battered', Hard: 'Dashi' } },
    { word: 'Ceviche', hints: { Easy: 'Lime', Medium: 'Peru', Hard: 'Leche' } },
    { word: 'Baklava', hints: { Easy: 'Sweet', Medium: 'Honey', Hard: 'Phyllo' } },
    { word: 'Risotto', hints: { Easy: 'Creamy', Medium: 'Italy', Hard: 'Arborio' } },
    { word: 'Gyoza', hints: { Easy: 'Dumpling', Medium: 'Japan', Hard: 'Potsticker' } },
  ],

  Movies: [
    { word: 'Titanic', hints: { Easy: 'Ship', Medium: 'DiCaprio', Hard: 'Iceberg' } },
    { word: 'Avatar', hints: { Easy: 'Blue', Medium: 'Pandora', Hard: 'Navi' } },
    { word: 'Inception', hints: { Easy: 'Dream', Medium: 'Spinning', Hard: 'Limbo' } },
    { word: 'Interstellar', hints: { Easy: 'Space', Medium: 'Wormhole', Hard: 'Tesseract' } },
    { word: 'Joker', hints: { Easy: 'Clown', Medium: 'Gotham', Hard: 'Phoenix' } },
    { word: 'Parasite', hints: { Easy: 'Rich', Medium: 'Basement', Hard: 'Bong' } },
    { word: 'Matrix', hints: { Easy: 'Pill', Medium: 'Simulation', Hard: 'Morpheus' } },
    { word: 'Gladiator', hints: { Easy: 'Arena', Medium: 'Rome', Hard: 'Maximus' } },
    { word: 'Shrek', hints: { Easy: 'Ogre', Medium: 'Swamp', Hard: 'Duloc' } },
    { word: 'Frozen', hints: { Easy: 'Ice', Medium: 'Elsa', Hard: 'Arendelle' } },
    { word: 'Jaws', hints: { Easy: 'Shark', Medium: 'Beach', Hard: 'Amity' } },
    { word: 'Rocky', hints: { Easy: 'Boxing', Medium: 'Training', Hard: 'Philadelphia' } },
    { word: 'Alien', hints: { Easy: 'Space', Medium: 'Chest', Hard: 'Xenomorph' } },
    { word: 'Psycho', hints: { Easy: 'Shower', Medium: 'Motel', Hard: 'Hitchcock' } },
    { word: 'Casablanca', hints: { Easy: 'Classic', Medium: 'Morocco', Hard: 'Rick' } },
    { word: 'Grease', hints: { Easy: 'Dancing', Medium: 'Pink Ladies', Hard: 'Rydell' } },
    { word: 'Goodfellas', hints: { Easy: 'Mafia', Medium: 'Henry', Hard: 'Wiseguy' } },
    { word: 'Braveheart', hints: { Easy: 'Scotland', Medium: 'Freedom', Hard: 'Wallace' } },
    { word: 'Scarface', hints: { Easy: 'Tony', Medium: 'Miami', Hard: 'Montana' } },
    { word: 'Forrest Gump', hints: { Easy: 'Running', Medium: 'Shrimp', Hard: 'Feather' } },
    { word: 'Pulp Fiction', hints: { Easy: 'Briefcase', Medium: 'Diner', Hard: 'Tarantino' } },
    { word: 'Up', hints: { Easy: 'Balloons', Medium: 'Adventure', Hard: 'Ellie' } },
    { word: 'Coco', hints: { Easy: 'Music', Medium: 'Mexico', Hard: 'Ofrenda' } },
    { word: 'Moana', hints: { Easy: 'Ocean', Medium: 'Hawaii', Hard: 'Maui' } },
    { word: 'Toy Story', hints: { Easy: 'Toys', Medium: 'Woody', Hard: 'Infinity' } },
    { word: 'Lion King', hints: { Easy: 'Africa', Medium: 'Simba', Hard: 'Mufasa' } },
    { word: 'Mulan', hints: { Easy: 'China', Medium: 'Warrior', Hard: 'Fa' } },
    { word: 'Aladdin', hints: { Easy: 'Lamp', Medium: 'Genie', Hard: 'Agrabah' } },
    { word: 'Beetlejuice', hints: { Easy: 'Ghost', Medium: 'Striped', Hard: 'Neitherworld' } },
    { word: 'Ghostbusters', hints: { Easy: 'Slimer', Medium: 'Proton', Hard: 'Zuul' } },
  ],

  Technology: [
    { word: 'Smartphone', hints: { Easy: 'Touch', Medium: 'App', Hard: 'Gorilla' } },
    { word: 'Internet', hints: { Easy: 'Online', Medium: 'Browser', Hard: 'Protocol' } },
    { word: 'Computer', hints: { Easy: 'Screen', Medium: 'Processor', Hard: 'Binary' } },
    { word: 'Robot', hints: { Easy: 'Machine', Medium: 'Automated', Hard: 'Actuator' } },
    { word: 'Satellite', hints: { Easy: 'Orbit', Medium: 'Signal', Hard: 'Geostationary' } },
    { word: 'Bluetooth', hints: { Easy: 'Wireless', Medium: 'Pairing', Hard: 'Harald' } },
    { word: 'Keyboard', hints: { Easy: 'Typing', Medium: 'QWERTY', Hard: 'Mechanical' } },
    { word: 'Camera', hints: { Easy: 'Photo', Medium: 'Lens', Hard: 'Aperture' } },
    { word: 'Battery', hints: { Easy: 'Power', Medium: 'Charging', Hard: 'Lithium' } },
    { word: 'Headphones', hints: { Easy: 'Audio', Medium: 'Noise', Hard: 'Impedance' } },
    { word: 'Drone', hints: { Easy: 'Flying', Medium: 'Remote', Hard: 'Quadcopter' } },
    { word: 'Laser', hints: { Easy: 'Beam', Medium: 'Light', Hard: 'Photon' } },
    { word: 'Microchip', hints: { Easy: 'Tiny', Medium: 'Silicon', Hard: 'Transistor' } },
    { word: 'Radar', hints: { Easy: 'Detection', Medium: 'Signal', Hard: 'Doppler' } },
    { word: 'Speaker', hints: { Easy: 'Sound', Medium: 'Volume', Hard: 'Woofer' } },
    { word: 'Microscope', hints: { Easy: 'Tiny', Medium: 'Biology', Hard: 'Magnification' } },
    { word: 'Telescope', hints: { Easy: 'Stars', Medium: 'Lens', Hard: 'Refracting' } },
    { word: 'GPS', hints: { Easy: 'Navigation', Medium: 'Satellite', Hard: 'Triangulation' } },
    { word: 'Touchscreen', hints: { Easy: 'Tap', Medium: 'Capacitive', Hard: 'Resistive' } },
    { word: 'Printer', hints: { Easy: 'Paper', Medium: 'Ink', Hard: 'Inkjet' } },
    { word: 'Router', hints: { Easy: 'WiFi', Medium: 'Network', Hard: 'Gateway' } },
    { word: 'Projector', hints: { Easy: 'Beam', Medium: 'Cinema', Hard: 'Lumens' } },
    { word: 'Scanner', hints: { Easy: 'Copy', Medium: 'Digital', Hard: 'Resolution' } },
    { word: 'Algorithm', hints: { Easy: 'Steps', Medium: 'Code', Hard: 'Complexity' } },
    { word: 'Cloud', hints: { Easy: 'Storage', Medium: 'Server', Hard: 'Infrastructure' } },
    { word: 'Firewall', hints: { Easy: 'Security', Medium: 'Network', Hard: 'Packet' } },
    { word: 'Processor', hints: { Easy: 'Brain', Medium: 'Speed', Hard: 'Cores' } },
    { word: 'Modem', hints: { Easy: 'Internet', Medium: 'Signal', Hard: 'Modulation' } },
    { word: 'Charger', hints: { Easy: 'Power', Medium: 'Cable', Hard: 'Wattage' } },
    { word: 'Webinar', hints: { Easy: 'Online', Medium: 'Meeting', Hard: 'Broadcast' } },
  ],

  Music: [
    { word: 'Guitar', hints: { Easy: 'Strings', Medium: 'Fret', Hard: 'Plectrum' } },
    { word: 'Piano', hints: { Easy: 'Keys', Medium: 'Ivory', Hard: 'Forte' } },
    { word: 'Drums', hints: { Easy: 'Beat', Medium: 'Rhythm', Hard: 'Paradiddle' } },
    { word: 'Violin', hints: { Easy: 'Bow', Medium: 'Orchestra', Hard: 'Rosin' } },
    { word: 'Trumpet', hints: { Easy: 'Brass', Medium: 'Jazz', Hard: 'Embouchure' } },
    { word: 'Microphone', hints: { Easy: 'Singing', Medium: 'Amplify', Hard: 'Diaphragm' } },
    { word: 'Album', hints: { Easy: 'Songs', Medium: 'Vinyl', Hard: 'LP' } },
    { word: 'Concert', hints: { Easy: 'Stage', Medium: 'Encore', Hard: 'Venue' } },
    { word: 'Melody', hints: { Easy: 'Tune', Medium: 'Notes', Hard: 'Motif' } },
    { word: 'Saxophone', hints: { Easy: 'Woodwind', Medium: 'Jazz', Hard: 'Adolphe' } },
    { word: 'Flute', hints: { Easy: 'Blow', Medium: 'Woodwind', Hard: 'Embouchure' } },
    { word: 'Cello', hints: { Easy: 'Strings', Medium: 'Orchestra', Hard: 'Endpin' } },
    { word: 'Harp', hints: { Easy: 'Angel', Medium: 'Pluck', Hard: 'Pedal' } },
    { word: 'Bass', hints: { Easy: 'Low', Medium: 'Groove', Hard: 'Subwoofer' } },
    { word: 'Conductor', hints: { Easy: 'Baton', Medium: 'Orchestra', Hard: 'Podium' } },
    { word: 'Chorus', hints: { Easy: 'Together', Medium: 'Refrain', Hard: 'Harmony' } },
    { word: 'Tempo', hints: { Easy: 'Speed', Medium: 'BPM', Hard: 'Andante' } },
    { word: 'Chord', hints: { Easy: 'Notes', Medium: 'Harmony', Hard: 'Triad' } },
    { word: 'Remix', hints: { Easy: 'New', Medium: 'DJ', Hard: 'Rework' } },
    { word: 'Vinyl', hints: { Easy: 'Record', Medium: 'Groove', Hard: 'RPM' } },
    { word: 'Synthesizer', hints: { Easy: 'Electronic', Medium: 'Keyboard', Hard: 'Oscillator' } },
    { word: 'Ukulele', hints: { Easy: 'Small', Medium: 'Hawaii', Hard: 'Nylon' } },
    { word: 'Trombone', hints: { Easy: 'Slide', Medium: 'Brass', Hard: 'Glissando' } },
    { word: 'Banjo', hints: { Easy: 'Country', Medium: 'Pluck', Hard: 'Resonator' } },
    { word: 'Accordion', hints: { Easy: 'Squeeze', Medium: 'Bellows', Hard: 'Reed' } },
    { word: 'Oboe', hints: { Easy: 'Reed', Medium: 'Orchestra', Hard: 'Tuning' } },
    { word: 'Xylophone', hints: { Easy: 'Mallet', Medium: 'Bars', Hard: 'Resonator' } },
    { word: 'Harmonica', hints: { Easy: 'Blow', Medium: 'Blues', Hard: 'Diatonic' } },
    { word: 'Mandolin', hints: { Easy: 'Strings', Medium: 'Folk', Hard: 'Tremolo' } },
    { word: 'Turntable', hints: { Easy: 'Spin', Medium: 'DJ', Hard: 'Stylus' } },
  ],

  'Random 🎲': [
    { word: 'Escalator', hints: { Easy: 'Moving', Medium: 'Mall', Hard: 'Handrail' } },
    { word: 'Stapler', hints: { Easy: 'Office', Medium: 'Bind', Hard: 'Anvil' } },
    { word: 'Compass', hints: { Easy: 'Direction', Medium: 'Needle', Hard: 'Declination' } },
    { word: 'Umbrella', hints: { Easy: 'Rain', Medium: 'Canopy', Hard: 'Ferrule' } },
    { word: 'Elevator', hints: { Easy: 'Floor', Medium: 'Shaft', Hard: 'Counterweight' } },
    { word: 'Bubble Wrap', hints: { Easy: 'Pop', Medium: 'Packaging', Hard: 'Polyethylene' } },
    { word: 'Vending Machine', hints: { Easy: 'Coins', Medium: 'Snack', Hard: 'Dispensing' } },
    { word: 'Traffic Cone', hints: { Easy: 'Orange', Medium: 'Road', Hard: 'Delineator' } },
    { word: 'Sticky Note', hints: { Easy: 'Yellow', Medium: 'Reminder', Hard: 'Adhesive' } },
    { word: 'Eraser', hints: { Easy: 'Mistake', Medium: 'Rubber', Hard: 'Abrasive' } },
    { word: 'Scissors', hints: { Easy: 'Cut', Medium: 'Blade', Hard: 'Pivot' } },
    { word: 'Magnifying Glass', hints: { Easy: 'Bigger', Medium: 'Detective', Hard: 'Convex' } },
    { word: 'Rubber Band', hints: { Easy: 'Stretch', Medium: 'Elastic', Hard: 'Latex' } },
    { word: 'Paperclip', hints: { Easy: 'Hold', Medium: 'Bent', Hard: 'Gem' } },
    { word: 'Tape', hints: { Easy: 'Sticky', Medium: 'Transparent', Hard: 'Adhesive' } },
    { word: 'Ruler', hints: { Easy: 'Measure', Medium: 'Straight', Hard: 'Calibration' } },
    { word: 'Calculator', hints: { Easy: 'Numbers', Medium: 'Button', Hard: 'Arithmetic' } },
    { word: 'Flashlight', hints: { Easy: 'Dark', Medium: 'Battery', Hard: 'Lumens' } },
    { word: 'Thermometer', hints: { Easy: 'Temperature', Medium: 'Mercury', Hard: 'Celsius' } },
    { word: 'Stopwatch', hints: { Easy: 'Time', Medium: 'Lap', Hard: 'Chronograph' } },
    { word: 'Padlock', hints: { Easy: 'Key', Medium: 'Secure', Hard: 'Shackle' } },
    { word: 'Funnel', hints: { Easy: 'Pour', Medium: 'Wide', Hard: 'Conical' } },
    { word: 'Bucket', hints: { Easy: 'Water', Medium: 'Handle', Hard: 'Pail' } },
    { word: 'Ladder', hints: { Easy: 'Climb', Medium: 'Rungs', Hard: 'Extension' } },
    { word: 'Pulley', hints: { Easy: 'Rope', Medium: 'Lift', Hard: 'Mechanical' } },
    { word: 'Compass Rose', hints: { Easy: 'Map', Medium: 'Direction', Hard: 'Cardinal' } },
    { word: 'Hourglass', hints: { Easy: 'Sand', Medium: 'Time', Hard: 'Ampoule' } },
    { word: 'Periscope', hints: { Easy: 'Submarine', Medium: 'Mirror', Hard: 'Prism' } },
    { word: 'Abacus', hints: { Easy: 'Beads', Medium: 'Count', Hard: 'Soroban' } },
    { word: 'Metronome', hints: { Easy: 'Tick', Medium: 'Music', Hard: 'Pendulum' } },
  ],
};

export function getRandomWord(topic: string, difficulty: 'Easy' | 'Medium' | 'Hard'): { word: string; hint: string } {
  const entries = wordBank[topic] || wordBank['Random 🎲'];
  const entry = entries[Math.floor(Math.random() * entries.length)];
  return { word: entry.word, hint: entry.hints[difficulty] };
}
